name: Build and Release

on:
    push:
        tags:
            - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
    build_desktop:
        name: Build Desktop on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --production

            # macOS-specific steps for code signing and notarization
            - name: Import Apple Developer Certificate (macOS only)
              if: matrix.os == 'macos-latest'
              env:
                  DEVELOPER_ID_CERT: ${{ secrets.DEVELOPER_ID_CERT }}
                  DEVELOPER_ID_CERT_PASSWORD: ${{ secrets.DEVELOPER_ID_CERT_PASSWORD }}
              run: |
                  echo "$DEVELOPER_ID_CERT" | base64 --decode > developer_id_certificate.p12
                  security create-keychain -p "" build.keychain
                  security default-keychain -s build.keychain
                  security unlock-keychain -p "" build.keychain
                  security import developer_id_certificate.p12 -k build.keychain -P "$DEVELOPER_ID_CERT_PASSWORD" -T /usr/bin/codesign
                  security set-key-partition-list -S apple-tool:,apple:,codesign: -s -k "" build.keychain

            - name: List Certificates in Keychain (macOS only)
              if: matrix.os == 'macos-latest'
              run: |
                  security find-identity -v -p codesigning

            - name: Build for Desktop
              uses: samuelmeuli/action-electron-builder@v1.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release: false # Prevent auto-release in electron-builder
              env:
                  DEBUG: electron-notarize*
                  APPLE_ID: ${{ secrets.APPLE_ID }}
                  APPLE_APP_SPECIFIC_PASSWORD: ${{ secrets.APPLE_ID_PASSWORD }}
                  APPLE_TEAM_ID: ${{ secrets.APPLE_TEAM_ID }}

            - name: Rename and Upload Artifacts
              run: |
                  VERSION=${{ github.ref_name }}
                  mkdir release

                  if [[ "$RUNNER_OS" == "Linux" ]]; then
                      mv dist/*.AppImage "release/screendeck-linux-x64-$VERSION.AppImage"
                  elif [[ "$RUNNER_OS" == "Windows" ]]; then
                      mv dist/*.exe "release/screendeck-windows-x64-$VERSION.exe"
                  elif [[ "$RUNNER_OS" == "macOS" ]]; then
                      mv dist/*-x64.dmg "release/screendeck-mac-intel-$VERSION.dmg" || true
                      mv dist/*-arm64.dmg "release/screendeck-mac-silicon-$VERSION.dmg" || true
                      mv dist/*-universal.dmg "release/screendeck-mac-universal-$VERSION.dmg" || true
                  fi

            - name: Upload Desktop Artifacts
              uses: actions/upload-artifact@v3
              with:
                  name: screendeck-desktop-${{ github.ref_name }}
                  path: release/*

    build_rpi:
        name: Build for Raspberry Pi (ARM64)
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v2

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20

            - name: Install dependencies
              run: yarn install --production

            - name: Build Electron App for ARM64
              run: |
                  yarn run electron-builder --linux --arm64

            - name: Rename ARM64 Artifact
              run: |
                  VERSION=${{ github.ref_name }}
                  mkdir release
                  mv dist/*.AppImage "release/screendeck-rpi-arm64-$VERSION.AppImage"

            - name: Upload ARM64 Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: screendeck-rpi-${{ github.ref_name }}
                  path: release/*

    release:
        name: Create GitHub Release
        runs-on: ubuntu-latest
        needs: [build_desktop, build_rpi]
        steps:
            - name: Download All Artifacts
              uses: actions/download-artifact@v3
              with:
                  path: release

            - name: Create GitHub Release
              uses: softprops/action-gh-release@v1
              with:
                  tag_name: ${{ github.ref_name }}
                  name: 'ScreenDeck v${{ github.ref_name }}'
                  body: "Official release of ScreenDeck v${{ github.ref_name}}.\n\nDownload the appropriate version for your OS below."
                  files: release/**/*
                  draft: true
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
