name: Build and Release

on:
    push:
        tags:
            - 'v*.*.*' # Trigger on version tags like v1.0.0

jobs:
    build_desktop:
        name: Build Desktop on ${{ matrix.os }}
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [windows-latest, macos-latest, ubuntu-latest]
        steps:
            - uses: actions/checkout@v3
            - name: Setup Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: 20
            - name: Install dependencies
              run: yarn install --production
            - name: Build and Release
              uses: samuelmeuli/action-electron-builder@v1.6.0
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  release: true
